# Generated by Django 5.1.4 on 2024-12-19 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_documento', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField()),
            ],
            options={
                'db_table': 'biblioteca_archivo',
            },
        ),
        migrations.CreateModel(
            name='BibliotecaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=10)),
                ('fecha_subida', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True)),
                ('url_origen', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'biblioteca_documento',
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Comunidad')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('titulo_documento', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('comunidad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='seguimientodocumentos.comunidad', verbose_name='Comunidad')),
            ],
            options={
                'verbose_name': 'Documentación',
                'verbose_name_plural': 'Documentaciones',
                'db_table': 'seguimientodocumentos_Documentacion',
                'ordering': ['tipo', 'categoria', 'titulo_documento'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existe', models.CharField(choices=[('Si', 'Sí Existe'), ('No', 'No Existe')], default='No', max_length=10, verbose_name='¿Existe el documento?')),
                ('fecha_registrado', models.DateField(auto_now_add=True, verbose_name='Fecha Registrado')),
                ('fecha_actualizado', models.DateField(blank=True, null=True, verbose_name='Fecha Actualizado')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('documentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='seguimientodocumentos.documentacion', verbose_name='Documentación relacionada')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'Seguimiento',
                'ordering': ['-fecha_actualizado'],
            },
        ),
    ]
