# Generated by Django 5.1.2 on 2024-11-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('titulo_documento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existe', models.CharField(choices=[('S', 'Si Existe'), ('N', 'No Existe')], default='S', max_length=1)),
                ('fecha_registrado', models.DateField(verbose_name='Fecha de Registro')),
                ('fecha_actualizado', models.DateField(verbose_name='Fecha Actualizada')),
                ('observaciones', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('documentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientodocumentos.documentacion')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'seguimiento',
                'ordering': ['fecha_registrado', '-fecha_actualizado'],
            },
        ),
    ]
