# Generated by Django 5.1.2 on 2024-11-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='titulo_documento',
            field=models.CharField(max_length=200, verbose_name='Titulo del Documento'),
        ),
    ]
