# Generated by Django 5.1.3 on 2024-11-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0002_alter_documentacion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='existe',
            field=models.CharField(choices=[('Si', 'Sí Existe'), ('No', 'No Existe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_actualizado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_registrado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
