# Generated by Django 5.1.3 on 2024-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0003_alter_seguimiento_existe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='existe',
            field=models.CharField(choices=[('Si', 'Sí Existe'), ('No', 'No Existe')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
