# Generated by Django 5.1.4 on 2024-12-28 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0003_alter_comunidad_options_bibliotecaarchivo_comunidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('actualizado', 'Actualizado')], default='pendiente', max_length=20, verbose_name='Estado del seguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientodocumentos.comunidad', verbose_name='Comunidad asociada'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado'),
        ),
        migrations.AlterModelTable(
            name='bibliotecaarchivo',
            table='biblioteca_biblioteca_archivo',
        ),
        migrations.AlterModelTable(
            name='bibliotecadocumento',
            table='biblioteca_biblioteca_documento',
        ),
    ]
