# Generated by Django 5.1.4 on 2024-12-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0004_seguimiento_estado_alter_seguimiento_comunidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='estado',
        ),
    ]
