# Generated by Django 5.1.4 on 2025-01-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0005_remove_seguimiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='existe',
            field=models.CharField(choices=[('Si', 'Si Existe'), ('No', 'No Existe')], default='No', max_length=2, verbose_name='¿Existe el documento?'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_actualizado',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha Actualizado'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_registrado',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Registrado'),
        ),
    ]
