# Generated by Django 5.1.3 on 2024-11-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0006_alter_seguimiento_titulo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='titulo_documento',
        ),
    ]
