# Generated by Django 5.1.4 on 2025-01-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0006_alter_seguimiento_existe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='usuarios',
            field=models.ManyToManyField(related_name='comunidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
