# Generated by Django 5.1.3 on 2024-11-30 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0007_remove_seguimiento_titulo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='documentacion',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='titulo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seguimiento', to='seguimientodocumentos.documentacion'),
        ),
    ]
