# Generated by Django 5.1.4 on 2025-01-16 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0007_comunidad_usuarios_alter_comunidad_administrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='comunidad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades_administradas', to=settings.AUTH_USER_MODEL, verbose_name='comunidades'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientodocumentos.comunidad', verbose_name='seguimientos'),
        ),
    ]
