# Generated by Django 5.1.4 on 2025-02-01 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0008_alter_comunidad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='usuarios',
            field=models.ManyToManyField(related_name='comunidade_seguimiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
