# Generated by Django 5.1.3 on 2024-11-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0008_remove_seguimiento_documentacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento',
            old_name='titulo_documento',
            new_name='documentacion',
        ),
    ]
