# Generated by Django 5.1.4 on 2025-04-14 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0009_alter_comunidad_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Comunidad'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='usuarios',
            field=models.ManyToManyField(related_name='comunidades_seguimiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
