# Generated by Django 5.1.3 on 2024-12-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0010_objeto_alter_seguimiento_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='objeto',
        ),
        migrations.AlterModelOptions(
            name='documentacion',
            options={'ordering': ['tipo', 'categoria', 'titulo_documento'], 'verbose_name': 'Documentación', 'verbose_name_plural': 'Documentaciones'},
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='documentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='seguimientodocumentos.documentacion', verbose_name='Documentación relacionada'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='existe',
            field=models.CharField(choices=[('Si', 'Sí Existe'), ('No', 'No Existe')], default='No', max_length=10, verbose_name='¿Existe el documento?'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_actualizado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Actualizado'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_registrado',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Registrado'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterModelTable(
            name='documentacion',
            table='documentacion',
        ),
    ]
