# Generated by Django 5.1.4 on 2024-12-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0011_delete_objeto_alter_documentacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='titulo_documento',
            field=models.CharField(max_length=200, verbose_name='Título del Documento'),
        ),
    ]
