# Generated by Django 5.1.4 on 2024-12-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientodocumentos', '0012_alter_documentacion_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='categoria',
            field=models.CharField(blank=True, default='Sin Categoría', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='titulo_documento',
            field=models.CharField(blank=True, default='Sin Titulo', max_length=255, null=True),
        ),
    ]
