[pytest]
# Dónde encontrar los settings de Django
DJANGO_SETTINGS_MODULE = Documentacion.settings
# Permite localizar automáticamente el proyecto Django
django_find_project = true

# Opciones adicionales al invocar pytest:
#  -v           : verbose
# --reuse-db    : reutilizar la base de datos de test si existe
# --disable-warnings : silenciar warnings
# --maxfail=1   : parar al primer fallo
addopts = -v --reuse-db --disable-warnings --maxfail=1

# Dónde buscar tests
testpaths = mantenimiento/tests

# Patrón de nombres de archivos de test
python_files = tests.py test_*.py *_tests.py

# Asegura que el root del proyecto esté en PYTHONPATH
pythonpath = .

# Marcadores personalizados
markers =
    asyncio: mark a test as async.
    asyncio_mode = auto

