# Generated by Django 5.1.4 on 2025-03-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguimientodocumentos', '0009_alter_comunidad_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Administracion', 'Administracion'), ('Contabilidad', 'Contabilidad'), ('Legal', 'Legal'), ('Mantenimiento', 'Mantenimiento'), ('Personal', 'Personal'), ('Prevencion de Riesgos', 'Prevencion de Riesgos'), ('Seguridad', 'Seguridad'), ('Otros', 'Otros')], max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('Comunicacion', 'Comunicacion'), ('Comunidad', 'Comunidad'), ('Contable', 'Contable'), ('Gastos Comunes', 'Gastos Comunes'), ('Gestion de Emergencia', 'Gestion de Emergencia'), ('Inmobiliaria', 'Inmobiliaria'), ('Leyes Laborales', 'Leyes Laborales'), ('Libros', 'Libros'), ('Mantenimiento Preventivo', 'Mantenimiento Preventivo'), ('Planos', 'Planos'), ('Proveedores', 'Proveedores'), ('Reglamentos', 'Reglamentos'), ('Resolucion de Conflictos', 'Resolucion de Conflictos'), ('Temas de Seguridad', 'Temas de Seguridad'), ('Otros', 'Otros')], max_length=100, null=True)),
                ('titulo_documento', models.CharField(max_length=255)),
                ('documento', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_biblioteca', to='seguimientodocumentos.comunidad')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='biblioteca/')),
                ('tipo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('url_origen', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=50)),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True)),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_documentos', to='seguimientodocumentos.comunidad')),
            ],
        ),
    ]
