# Generated by Django 5.1.4 on 2025-03-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
    ]
