# Generated by Django 5.1.4 on 2024-12-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_descarga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='url_origen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='biblioteca/'),
        ),
    ]
