# Generated by Django 5.1.4 on 2025-04-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20250319_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
