# Generated by Django 5.1.4 on 2025-06-03 22:20
# biblioteca/migrations/0004_categoriadocumento_tipodocumento_and_more.py

import django.db.models.deletion
from django.db import migrations, models

def trasladar_tipos_texto_a_fk(apps, schema_editor):
    """
    1) Recoge todos los valores únicos de Archivo.tipo (que en ese momento sigue siendo CharField).
    2) Crea (o recupera) en TipoDocumento una fila con nombre=ese texto.
    3) Actualiza cada Archivo.tipo (texto) asignándole el id del TipoDocumento correspondiente.
    """
    Archivo = apps.get_model('biblioteca', 'Archivo')
    TipoDocumento = apps.get_model('biblioteca', 'TipoDocumento')

    # a) Todos los textos distintos en Archivo.tipo que no sean nulos ni vacíos
    tipos_texto = (
        Archivo.objects
        .exclude(tipo__isnull=True)
        .exclude(tipo='')
        .values_list('tipo', flat=True)
        .distinct()
    )

    # b) Creamos o recuperamos un TipoDocumento por cada texto distinto
    mapping = {}  # map[texto_original] = id_del_TipoDocumento
    for texto in tipos_texto:
        tipo_obj, _ = TipoDocumento.objects.get_or_create(nombre=texto)
        mapping[texto] = tipo_obj.id

    # c) Recorremos todos los archivos y reasignamos el campo tipo (que aún es CharField)
    #    a su nuevo valor numérico (el FK). Si no hay mapeo, ponemos NULL.
    for archivo in Archivo.objects.all():
        texto_original = archivo.tipo
        if texto_original in mapping:
            archivo.tipo = mapping[texto_original]
        else:
            archivo.tipo = None
        archivo.save(update_fields=['tipo'])


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('biblioteca', '0003_alter_archivo_documento'),
        ('seguimientodocumentos', '0012_delete_profile'),
    ]

    operations = [
        # ─── 1) Creamos la tabla TipoDocumento ───────────────────────────────────────
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),

        # ─── 2) Creamos la tabla CategoriaDocumento ─────────────────────────────────
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                # El campo 'tipo' (FK) se agregará con AddField abajo
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documento',
                # Esta opción de ordering (tipo__nombre) no llegará a aplicarse
                # hasta después de que exista el FK 'tipo'.
                'ordering': ['tipo__nombre', 'nombre'],
            },
        ),

        # ─── 3) Trasladamos los valores de texto que había en Archivo.tipo a la nueva tabla TipoDocumento ──────
        migrations.RunPython(trasladar_tipos_texto_a_fk, reverse_code=migrations.RunPython.noop),

        # ─── 4) Convertimos comunidad en Archivo a ForeignKey ────────────────────────────
        migrations.AlterField(
            model_name='archivo',
            name='comunidad',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='archivos_biblioteca',
                to='seguimientodocumentos.comunidad'
            ),
            preserve_default=False,
        ),

        # ─── 5) *Antes* de cambiar 'categoria' a FK, eliminamos cualquier texto que quede ahí ──────────────
        migrations.RunSQL(
            sql="UPDATE biblioteca_archivo SET categoria = NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),

        # ─── 6) Convertimos campo categoria (antes CharField) → FK a CategoriaDocumento ───────────────────
        migrations.AlterField(
            model_name='archivo',
            name='categoria',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='archivos',
                to='biblioteca.categoriadocumento'
            ),
        ),

        # ─── 7) Agregamos la relación tipo en CategoriaDocumento → FK a TipoDocumento ──────────────────────
        migrations.AddField(
            model_name='categoriadocumento',
            name='tipo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categorias',
                to='biblioteca.tipodocumento'
            ),
        ),

        # ─── 8) Convertimos campo tipo en Archivo (antes CharField) → FK a TipoDocumento ──────────────────
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='archivos',
                to='biblioteca.tipodocumento'
            ),
        ),

        # ─── 9) Ahora sí aplicamos el ordering que une con campos relacionados ─────────────────────────────
        migrations.AlterModelOptions(
            name='archivo',
            options={'ordering': ['tipo__nombre', 'categoria__nombre', 'titulo_documento']},
        ),

        # ── 10) Hacemos (tipo, nombre) único en CategoriaDocumento ────────────────────────────────────────
        migrations.AlterUniqueTogether(
            name='categoriadocumento',
            unique_together={('tipo', 'nombre')},
        ),
    ]
