# Generated by Django 5.1.4 on 2024-12-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_archivo_options_alter_archivo_categoria_and_more'),
        ('seguimientodocumentos', '0003_alter_comunidad_options_bibliotecaarchivo_comunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_documentos', to='seguimientodocumentos.comunidad'),
        ),
    ]
