# Generated by Django 5.1.4 on 2025-01-09 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_documento_comunidad'),
        ('seguimientodocumentos', '0006_alter_seguimiento_existe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_biblioteca', to='seguimientodocumentos.comunidad'),
        ),
    ]
