# Generated by Django 5.1.4 on 2025-02-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('seguimientodocumentos', '0009_alter_comunidad_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomantenimiento',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='seguimientodocumentos.comunidad'),
        ),
        migrations.AddField(
            model_name='cotizacionproveedor',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='seguimientodocumentos.comunidad'),
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='seguimientodocumentos.comunidad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='seguimientodocumentos.comunidad'),
        ),
        migrations.AddField(
            model_name='reparaciongeneral',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='seguimientodocumentos.comunidad'),
        ),
    ]
