# Generated by Django 5.1.4 on 2025-03-03 19:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_contratomantenimiento_comunidad_and_more'),
        ('seguimientodocumentos', '0009_alter_comunidad_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mantencionpreventiva',
            old_name='fecha',
            new_name='fecha_programada',
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='custom_category',
            field=models.CharField(blank=True, help_text='Usa este campo si no se encuentra la categoría predefinida.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='fecha_realizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mantencionpreventiva',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientodocumentos.comunidad'),
        ),
        migrations.AlterField(
            model_name='mantencionpreventiva',
            name='instalacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.installationcategory'),
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantencionpreventiva')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
