# Generated by Django 5.1.4 on 2025-03-04 13:41

from django.db import migrations

def create_installation_categories(apps, schema_editor):
    InstallationCategory = apps.get_model('mantenimiento', 'InstallationCategory')
    categories = [
        {"name": "Caldera", "description": "Instalación para calderas."},
        {"name": "Bomba de Agua", "description": "Instalación para bombas de agua."},
        {"name": "Ascensores", "description": "Instalación para ascensores."},
        {"name": "Jardines", "description": "Instalación para jardines."},
        {"name": "Piscina", "description": "Instalación para piscinas."},
    ]
    
    InstallationCategory.objects.bulk_create([InstallationCategory(**cat) for cat in categories])
    print("Categorías insertadas correctamente")


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_installationcategory_and_more'),
    ]

    operations = [
        migrations.RunPython(create_installation_categories),
    ]
