# Generated by Django 5.1.4 on 2025-03-04 18:48

import mantenimiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_instalacionpreventiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacionpreventiva',
            name='fecha_instalacion',
            field=models.DateField(default=mantenimiento.models.fecha_actual),
        ),
    ]
