# Generated by Django 5.1.4 on 2025-03-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_instalacionpreventiva_instalacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacionpreventiva',
            name='mantencion',
            field=models.OneToOneField(help_text='Mantención preventiva asociada', on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='mantenimiento.mantencionpreventiva'),
        ),
    ]
