# Generated by Django 5.1.4 on 2025-03-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_remove_installationcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacionpreventiva',
            options={'verbose_name': 'Instalación Preventiva', 'verbose_name_plural': 'Instalaciones Preventivas'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['fecha_vencimiento'], 'verbose_name': 'Tarea de Mantenimiento', 'verbose_name_plural': 'Tareas de Mantenimiento'},
        ),
        migrations.AlterModelOptions(
            name='mantencionpreventiva',
            options={'verbose_name': 'Mantención Preventiva', 'verbose_name_plural': 'Mantenciones Preventivas'},
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='periodo',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', help_text='Frecuencia con la que se repite la mantención.', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionpreventiva',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En Revisión'), ('proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', help_text='Estado de la mantención en el tablero Kanban.', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En Revisión'), ('proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
