# Generated by Django 5.1.4 on 2025-03-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_alter_instalacionpreventiva_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacionpreventiva',
            name='responsable',
            field=models.CharField(blank=True, help_text='Responsable de la mantención.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mantencionpreventiva',
            name='responsable',
            field=models.CharField(blank=True, help_text='Ingrese el nombre del responsable de la mantención.', max_length=200, null=True),
        ),
    ]
