# Generated by Django 5.1.4 on 2025-03-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_alter_instalacionpreventiva_responsable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantencionpreventiva',
            options={'ordering': ['instalacion', 'fecha_programada'], 'verbose_name': 'Mantención Preventiva', 'verbose_name_plural': 'Mantenciones Preventivas'},
        ),
    ]
