# Generated by Django 5.1.4 on 2025-03-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0012_alter_mantencionpreventiva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['fecha_programada'], 'verbose_name': 'Tarea de Mantenimiento', 'verbose_name_plural': 'Tareas de Mantenimiento'},
        ),
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='fecha_vencimiento',
            new_name='fecha_programada',
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='fecha_realizada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='mantencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mantenimiento.mantencionpreventiva'),
        ),
    ]
