# Generated by Django 5.1.4 on 2025-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0013_alter_maintenancetask_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cotizacionproveedor',
            name='comunidad',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='comunidad',
        ),
        migrations.RemoveField(
            model_name='reparaciongeneral',
            name='comunidad',
        ),
        migrations.DeleteModel(
            name='ContratoMantenimiento',
        ),
        migrations.DeleteModel(
            name='CotizacionProveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='ReparacionGeneral',
        ),
    ]
