# Generated by Django 5.1.4 on 2025-03-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0014_mantenimiento_remove_cotizacionproveedor_comunidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En Revisión'), ('proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', help_text='Estado del mantenimiento.', max_length=20),
        ),
    ]
