# Generated by Django 5.1.4 on 2025-04-14 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0015_alter_mantenimiento_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installationcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoría de Instalación', 'verbose_name_plural': 'Categorías de Instalación'},
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='mantencion',
            field=models.OneToOneField(default=2, help_text='Relación con la mantención preventiva.', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_extendido', to='mantenimiento.mantencionpreventiva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installationcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Instalación'),
        ),
        migrations.AlterField(
            model_name='mantencionpreventiva',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
