# Generated by Django 5.1.4 on 2025-05-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0016_alter_installationcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='mantencion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimiento_extendido', to='mantenimiento.mantencionpreventiva'),
        ),
    ]
