# Generated by Django 5.1.4 on 2025-02-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguimientodocumentos', '0009_alter_comunidad_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Residente')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='seguimientodocumentos.comunidad')),
            ],
        ),
    ]
