# Generated by Django 5.1.4 on 2025-02-12 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0002_archivo_correoadjunto_destinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinatario',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Destinatario', 'verbose_name_plural': 'Destinatarios'},
        ),
        migrations.AddField(
            model_name='destinatario',
            name='apellido',
            field=models.CharField(default='', max_length=255, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
