# Generated by Django 5.1.4 on 2025-02-20 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0003_alter_destinatario_options_destinatario_apellido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
